// Run with:  npm run images
// Looks in assets/food and assets/characters, and writes src/images.js so the app can use your PNGs.
// Food file names: recipe id + .png. Capitals, spaces, dashes and a trailing number are ignored,
// so "Ramen.png", "cake1.png" and "Bento Box.png" all work.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const foodDir = path.join(root, 'assets', 'food');
const charDir = path.join(root, 'assets', 'characters');

const list = (dir) =>
  fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => /\.png$/i.test(f)).sort() : [];

// "Cookie Skillet2.png" -> "cookieskillet"
const clean = (fileName) => fileName.replace(/\.png$/i, '').toLowerCase().replace(/[^a-z0-9]/g, '').replace(/\d+$/, '');

// Read the recipe ids out of src/data.js
const data = fs.readFileSync(path.join(root, 'src', 'data.js'), 'utf8');
const recipeIds = [...data.matchAll(/id: '(\w+)'.*bakeSec/g)].map((m) => m[1]);

const foodFiles = list(foodDir);
const charFiles = list(charDir);

const chosen = {}; // recipe id -> file name
for (const f of foodFiles) {
  const id = clean(f);
  if (!recipeIds.includes(id)) {
    console.log(`⚠️  assets/food/${f} does not match any recipe, so it was skipped. Rename it to one of: ${recipeIds.join(', ')}`);
    continue;
  }
  if (chosen[id]) {
    console.log(`⚠️  Two files match "${id}": ${chosen[id]} and ${f}. Using ${f}.`);
  }
  chosen[id] = f;
}

const foodLines = Object.entries(chosen).map(([id, f]) => `  ${id}: require('../assets/food/${f}'),`);
const charLines = charFiles.map((f) => `  require('../assets/characters/${f}'),`);

const out = `// AUTO-GENERATED by "npm run images". Do not edit by hand.
export const FOOD_IMAGES = {
${foodLines.join('\n')}
};

export const CHARACTER_IMAGES = [
${charLines.join('\n')}
];
`;
fs.writeFileSync(path.join(root, 'src', 'images.js'), out);

const used = Object.keys(chosen);
console.log(`Food PNGs used: ${used.length} of ${recipeIds.length}`);
const missing = recipeIds.filter((id) => !used.includes(id));
if (missing.length) console.log(`Still using emoji for: ${missing.join(', ')}`);
console.log(`Character PNGs: ${charFiles.length}${charFiles.length === 0 ? ' (using emoji animals)' : ''}`);