// Run with:  npm run images
// Looks in assets/food, assets/characters and assets/backgrounds, and writes src/images.js
// so the app can use your PNGs.
// Food file names: recipe id + .png. Capitals, spaces, dashes and a trailing number are ignored,
// so "Ramen.png", "cake1.png" and "Bento Box.png" all work.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const foodDir = path.join(root, 'assets', 'food');
const charDir = path.join(root, 'assets', 'characters');
const bgDir = path.join(root, 'assets', 'backgrounds');

const list = (dir) =>
  fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => /\.png$/i.test(f)) : [];

// The bundler only recognises a lowercase ".png" extension — "ICEDMACT.PNG" fails to build.
// If a file's extension isn't exactly lowercase ".png", make a same-folder copy that is, and
// use that copy instead. The original file is left untouched.
const ensureLowerExt = (dir, file) => {
  if (file.endsWith('.png')) return file;
  const fixed = file.slice(0, -4) + '.png';
  fs.copyFileSync(path.join(dir, file), path.join(dir, fixed));
  return fixed;
};

// "Cookie Skillet2.png" -> "cookieskillet"  (used only for matching food to a recipe id)
const clean = (fileName) => fileName.replace(/\.png$/i, '').toLowerCase().replace(/[^a-z0-9]/g, '').replace(/\d+$/, '');

// Sorts "background2.png" before "background10.png" (plain alphabetical would get that backwards).
const naturalSort = (files) =>
  [...files].sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

// "background2.png" -> "Background 2", "cozy_wall.png" -> "Cozy Wall"
const label = (fileName) => {
  const base = fileName.replace(/\.png$/i, '').replace(/[_-]+/g, ' ');
  const spaced = base.replace(/([a-z])([A-Z0-9])/g, '$1 $2').replace(/\s+/g, ' ').trim();
  return spaced.replace(/\b\w/g, (c) => c.toUpperCase());
};

// Read the recipe ids out of src/data.js
const data = fs.readFileSync(path.join(root, 'src', 'data.js'), 'utf8');
const recipeIds = [...data.matchAll(/id: '(\w+)'.*bakeSec/g)].map((m) => m[1]);

const foodFiles = [...new Set(list(foodDir).map((f) => ensureLowerExt(foodDir, f)))];
const charFiles = naturalSort([...new Set(list(charDir).map((f) => ensureLowerExt(charDir, f)))]);
const bgFiles = naturalSort([...new Set(list(bgDir).map((f) => ensureLowerExt(bgDir, f)))]);

const chosen = {}; // recipe id -> file name
for (const f of foodFiles) {
  const id = clean(f);
  if (!recipeIds.includes(id)) {
    console.log(`⚠️  assets/food/${f} does not match any recipe, so it was skipped. Rename it to one of: ${recipeIds.join(', ')}`);
    continue;
  }
  if (chosen[id]) {
    console.log(`⚠️  Two files match "${id}": ${chosen[id]} and ${f}. Using ${f}.`);
  }
  chosen[id] = f;
}

const foodLines = Object.entries(chosen).map(([id, f]) => `  ${id}: require('../assets/food/${f}'),`);
const charLines = charFiles.map((f) => `  require('../assets/characters/${f}'),`);
const bgLines = bgFiles.map(
  (f, i) => `  { id: ${JSON.stringify(f)}, name: ${JSON.stringify(label(f))}, source: require('../assets/backgrounds/${f}') },`,
);

const out = `// AUTO-GENERATED by "npm run images". Do not edit by hand.
export const FOOD_IMAGES = {
${foodLines.join('\n')}
};

export const CHARACTER_IMAGES = [
${charLines.join('\n')}
];

// Every PNG in assets/backgrounds, in file order. Pick one in the Decorate tab in-game.
export const SCENE_BACKGROUNDS = [
${bgLines.join('\n')}
];
`;
fs.writeFileSync(path.join(root, 'src', 'images.js'), out);

const used = Object.keys(chosen);
console.log(`Food PNGs used: ${used.length} of ${recipeIds.length}`);
const missing = recipeIds.filter((id) => !used.includes(id));
if (missing.length) console.log(`Still using emoji for: ${missing.join(', ')}`);
console.log(`Character PNGs: ${charFiles.length}${charFiles.length === 0 ? ' (using emoji animals)' : ''}`);
console.log(`Background PNGs: ${bgFiles.length}${bgFiles.length === 0 ? ' (using wall/floor colours)' : ''}`);