// AUTO-GENERATED by "npm run images". Do not edit by hand.
export const FOOD_IMAGES = {
  black: require('../assets/food/BLACK.png'),
  chamolie: require('../assets/food/CHAMOLIE.png'),
  flower: require('../assets/food/FLOWER.png'),
  iced: require('../assets/food/ICED.png'),
  icedmact: require('../assets/food/ICEDMACT.png'),
  latte: require('../assets/food/LATTE.png'),
  straw: require('../assets/food/STRAW.png'),
  tea: require('../assets/food/TEA.png'),
};

export const CHARACTER_IMAGES = [

];

// Every PNG in assets/backgrounds, in file order. Pick one in the Decorate tab in-game.
export const SCENE_BACKGROUNDS = [
  { id: "background12.png", name: "Background 12", source: require('../assets/backgrounds/background12.png') },
  { id: "background13.png", name: "Background 13", source: require('../assets/backgrounds/background13.png') },
  { id: "background14.png", name: "Background 14", source: require('../assets/backgrounds/background14.png') },
  { id: "background15.png", name: "Background 15", source: require('../assets/backgrounds/background15.png') },
  { id: "background16.png", name: "Background 16", source: require('../assets/backgrounds/background16.png') },
  { id: "background17.png", name: "Background 17", source: require('../assets/backgrounds/background17.png') },
  { id: "background18.png", name: "Background 18", source: require('../assets/backgrounds/background18.png') },
  { id: "background20.png", name: "Background 20", source: require('../assets/backgrounds/background20.png') },
  { id: "background22.png", name: "Background 22", source: require('../assets/backgrounds/background22.png') },
  { id: "background24.png", name: "Background 24", source: require('../assets/backgrounds/background24.png') },
];
