// AUTO-GENERATED by "npm run images". Do not edit by hand.
export const FOOD_IMAGES = {
  agedashitofu: require('../assets/food/AgedashiTofu.png'),
  bentobox: require('../assets/food/BentoBox.png'),
  cookieskillet: require('../assets/food/CookieSkillet.png'),
  mooncake: require('../assets/food/Mooncake.png'),
  noodles: require('../assets/food/Noodles.png'),
  onigiri: require('../assets/food/Onigiri.png'),
  ramen: require('../assets/food/Ramen.png'),
  cake: require('../assets/food/cake1.png'),
};

export const CHARACTER_IMAGES = [

];
